"""Constants for the Climate Manager integration."""

DOMAIN = "climate_manager"
CONF_MQTT_BASE = "mqtt_base"
CONF_ROOM_SENSOR = "room_sensor"
DEFAULT_MQTT_BASE = "panasonic_heat_pump"

PLATFORMS = ["sensor", "switch", "number", "select", "text"]

# Read topics (relative to base)
TOPIC_HEATPUMP_STATE = "main/Heatpump_State"
TOPIC_OPERATING_MODE = "main/Operating_Mode_State"
TOPIC_DEFROSTING = "main/Defrosting_State"
TOPIC_QUIET_MODE = "main/Quiet_Mode_Level"
TOPIC_OUTSIDE_TEMP = "main/Outside_Temp"
TOPIC_OUTSIDE_PIPE_TEMP = "main/Outside_Pipe_Temp"
TOPIC_INLET_TEMP = "main/Main_Inlet_Temp"
TOPIC_OUTLET_TEMP = "main/Main_Outlet_Temp"
TOPIC_TARGET_TEMP = "main/Main_Target_Temp"
TOPIC_Z1_HEAT_REQUEST = "main/Z1_Heat_Request_Temp"
TOPIC_Z1_WATER_TEMP = "main/Z1_Water_Temp"
TOPIC_COMPRESSOR_FREQ = "main/Compressor_Freq"
TOPIC_PUMP_FLOW = "main/Pump_Flow"
TOPIC_PUMP_SPEED = "main/Pump_Speed"
TOPIC_MAX_PUMP_DUTY = "main/Max_Pump_Duty"
TOPIC_3WAY_VALVE = "main/ThreeWay_Valve_State"
TOPIC_HEAT_POWER_PRODUCED = "main/Heat_Power_Production"
TOPIC_HEAT_POWER_CONSUMED = "main/Heat_Power_Consumption"
TOPIC_OPERATING_HOURS = "main/Operations_Hours"
TOPIC_START_STOP_COUNTER = "main/Operations_Counter"
TOPIC_LAST_ERROR = "main/Error"
TOPIC_FAN1_SPEED = "main/Fan1_Motor_Speed"
TOPIC_FAN2_SPEED = "main/Fan2_Motor_Speed"
TOPIC_COMPRESSOR_CURRENT = "main/Compressor_Current"
TOPIC_HEATING_MODE = "main/Heating_Mode"
TOPIC_Z1_SENSOR_SETTINGS = "main/Z1_Sensor_Settings"
TOPIC_PUMP_FLOWRATE_MODE = "main/Pump_Flowrate_Mode"
TOPIC_OT_ROOM_TEMP_ECHO = "opentherm/write/roomTemp"
TOPIC_OT_ROOM_SETPOINT_ECHO = "opentherm/write/roomTempSet"

# Command topics
CMD_SET_HEATPUMP = "commands/SetHeatpump"
CMD_SET_QUIET_MODE = "commands/SetQuietMode"
CMD_SET_OPERATION_MODE = "commands/SetOperationMode"
CMD_SET_DHW_TEMP = "commands/SetDHWTemp"
CMD_OT_ROOM_TEMP = "opentherm/read/roomTemp"
CMD_OT_ROOM_SETPOINT = "opentherm/read/roomTempSet"
